[project]
name = "pyjour"
version = "0.0.0"
authors = [
    { name = "Quentin Richert", email = "noreply@richert.co" },
]
description = "Extract first names with confidence scores."
readme = "README.md"
requires-python = ">=3.12"
license = "0BSD"
license-files = ["LICENSE"]
keywords = ["first-name", "name-extraction", "person-name", "nlp", "classification"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
]

[project.urls]
Homepage = "https://github.com/qrichert/bonjour"
Repository = "https://github.com/qrichert/bonjour.git"

[project.scripts]
pyjour = "pyjour.main:main"

[tool.setuptools]
packages = ["pyjour"]

[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "zstandard==0.25.0",
]
